name: AALegacy
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - numpy=2.2
    - astropy=7.0
    - astroquery=0.4
    - pandas=2.3
    - scipy=1.15
    - matplotlib=3.10
    - photutils=2.2
    - regions=0.10
    - jupyter
    - pip
