name: AALegacy
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.13
    - numpy=2.2
    - astropy=7.0
    - scipy=1.15
    - matplotlib=3.10
    - regions=0.1
    - photutils=2.2
    - specutils=1.20
