name: AALegacy
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - numpy=2.2
    - astropy=7.0
    - astroquery=0.4
    - scipy=1.15
    - matplotlib=3.10
    - photutils=2.2
    - specutils=1.20
    - spectral-cube=0.6
    - regions=0.10
    - reproject=0.14
    - jupyter
    - pip
    - pip:
        - radio-beam==0.3.8
